/** Known service-layer error codes mapped in stronHttpError.util. */
export type StronErrorCode =
  | "invalid_ticket"
  | "invalid_tickets"
  | "invalid_marathon_mode"
  | "destination_required"
  | "successful_days_required"
  | "unknown_format"
  | "invalid_dates"
  | "invalid_capacity"
  | "invalid_price"
  | "invalid_amount"
  | "invalid_field"
  | "validation_error"
  | "registration_closed"
  | "sold_out"
  | "already_registered"
  | "participant_info_required"
  | "invalid_coupon"
  | "invalid_state"
  | "invalid_qr"
  | "invalid_type"
  | "bad_request"
  | "trial_not_eligible"
  | "trial_via_store_only"
  | "plan_stopped"
  | "plan_not_active"
  | "auto_renew_not_allowed"
  | "invalid_plan_status_transition"
  | "payment_failed"
  | "payment_not_configured"
  | "service_unavailable"
  | "payment_auth_failed"
  | "organizer_not_verified"
  | "organizer_profile_missing"
  | "organizer_suspended"
  | "business_suspended"
  | "kyc_incomplete"
  | "not_owner"
  | "organizer_cannot_enroll"
  | "listing_limit_reached"
  | "not_enrolled"
  | "membership_expired"
  | "no_membership"
  | "forbidden"
  | "unauthorized"
  | "not_found"
  | "opinion_not_found"
  | "user_not_found"
  | "organizer_not_found"
  | "business_not_found"
  | "member_not_found"
  | "plan_not_found"
  | "membership_not_found"
  | "coupon_not_found"
  | "payment_not_found"
  | "payout_account_not_found"
  | "event_not_found"
  | "participation_not_found"
  | "settlement_not_found"
  | "reward_not_found"
  | "duplicate"
  | "conflict"
  | "slug_taken"
  | "brand_page_not_found"
  | "staff_not_found"
  | "staff_already_exists"
  | "invalid_split"
  | "proposal_not_pending"
  | "insufficient_whatsapp_credits"
  | "reminder_config_not_found"
  | "whatsapp_not_entitled"
  | "whatsapp_provider_rejected"
  | "phone_already_linked"
  | "reminder_cooldown"
  | "attendance_already_marked"
  | "already_checked_in"
  | "internal_error"
  | "invalid_phone"
  | "invalid_otp"
  | "cooldown"
  | "hourly_limit"
  | "minute_limit"
  | "expired"
  | "otp_limit"
  | "provider_error"
  | "rate_limited"
  | "firebase_token_invalid";

export type CodedError = Error & { code: StronErrorCode };

export const isCodedError = (error: unknown): error is CodedError =>
  error instanceof Error &&
  typeof (error as CodedError).code === "string";

export const getErrorCode = (error: unknown): string | undefined =>
  isCodedError(error) ? error.code : undefined;
