import React from "react";
import { Redirect, useLocalSearchParams } from "expo-router";
import { href } from "@/navigation/href";

/**
 * Catches deep links like stron://event/[key] (generated by shared links)
 * and redirects them to the actual event screen path.
 */
const EventDeepLinkRedirect = () => {
  const { key } = useLocalSearchParams<{ key: string }>();

  if (!key) {
    return <Redirect href={href.splash} />;
  }

  return <Redirect href={{ pathname: href.app.stronEvent, params: { key } } as never} />;
};

export default EventDeepLinkRedirect;
