// Typography: Helvetica throughout entire application. Even sizes 8–64.

import { TextStyle, Platform } from "react-native";
import { colors } from "./colors";

/** Body / UI copy — Helvetica */
export const fontFamily = {
  light: "Helvetica",
  regular: "Helvetica",
  medium: "Helvetica",
  semiBold: "Helvetica",
  bold: "Helvetica",
  extraBold: "Helvetica",
} as const;

/** Headings, titles, hero text — Helvetica */
export const headingFontFamily = {
  regular: "Helvetica",
  medium: "Helvetica",
  semiBold: "Helvetica",
  semiBoldItalic: "Helvetica",
  bold: "Helvetica",
  extraBold: "Helvetica",
} as const;

const _base: TextStyle = { color: colors.headingText };

export const fontTextStyles: Record<string, TextStyle> = {
  // 8px (eight*)
  eightLightBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  eightNormalBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  eightMediumBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  eightSemiBoldBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  eightBoldBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  eightExtraBoldBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 10px (ten*)
  tenLightBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  tenNormalBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  tenMediumBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  tenSemiBoldBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  tenBoldBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  tenExtraBoldBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 12px (twelve*)
  twelveLightBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  twelveNormalBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  twelveMediumBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  twelveSemiBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  twelveBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  twelveExtraBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 12px (fourteen*)
  fourteenLightBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  fourteenNormalBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  fourteenMediumBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  fourteenSemiBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  fourteenBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  fourteenExtraBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 14px (sixteen*)
  sixteenLightBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  sixteenNormalBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  sixteenMediumBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  sixteenSemiBoldBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  sixteenBoldBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  sixteenExtraBoldBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 16px (eighteen*)
  eighteenLightBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  eighteenNormalBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  eighteenMediumBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  eighteenSemiBoldBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  eighteenBoldBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  eighteenExtraBoldBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 18px (twentyTwo*)
  twentyTwoLightBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  twentyTwoNormalBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  twentyTwoMediumBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  twentyTwoSemiBoldBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  twentyTwoBoldBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  twentyTwoExtraBoldBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 20px (twentyFour*)
  twentyFourLightBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  twentyFourNormalBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  twentyFourMediumBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  twentyFourSemiBoldBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  twentyFourBoldBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  twentyFourExtraBoldBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 22px (size24*)
  size24LightBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size24NormalBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size24MediumBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size24SemiBoldBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size24BoldBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size24ExtraBoldBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 24px (twentyEight*)
  twentyEightLightBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  twentyEightNormalBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  twentyEightMediumBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  twentyEightSemiBoldBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  twentyEightBoldBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  twentyEightExtraBoldBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 26px (thirty*)
  thirtyLightBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  thirtyNormalBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  thirtyMediumBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  thirtySemiBoldBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  thirtyBoldBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  thirtyExtraBoldBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 28px (size30*)
  size30LightBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size30NormalBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size30MediumBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size30SemiBoldBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size30BoldBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size30ExtraBoldBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 30px (thirtyTwo*)
  thirtyTwoLightBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  thirtyTwoNormalBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  thirtyTwoMediumBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  thirtyTwoSemiBoldBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  thirtyTwoBoldBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  thirtyTwoExtraBoldBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 32px (thirtyFour*)
  thirtyFourLightBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  thirtyFourNormalBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  thirtyFourMediumBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  thirtyFourSemiBoldBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  thirtyFourBoldBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  thirtyFourExtraBoldBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 34px (thirtySix*)
  thirtySixLightBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  thirtySixNormalBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  thirtySixMediumBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  thirtySixSemiBoldBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  thirtySixBoldBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  thirtySixExtraBoldBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 38px (size38*)
  size38LightBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size38NormalBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size38MediumBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size38SemiBoldBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size38BoldBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size38ExtraBoldBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 40px (size40*)
  size40LightBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size40NormalBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size40MediumBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size40SemiBoldBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size40BoldBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size40ExtraBoldBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 42px (size42*)
  size42LightBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size42NormalBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size42MediumBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size42SemiBoldBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size42BoldBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size42ExtraBoldBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 46px (size46*)
  size46LightBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size46NormalBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size46MediumBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size46SemiBoldBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size46BoldBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size46ExtraBoldBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 48px (size48*)
  size48LightBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size48NormalBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size48MediumBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size48SemiBoldBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size48BoldBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size48ExtraBoldBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 56px (size56*)
  size56LightBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size56NormalBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size56MediumBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size56SemiBoldBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size56BoldBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size56ExtraBoldBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 64px (size64*)
  size64LightBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: fontFamily.light,
    fontWeight: "300",
  },
  size64NormalBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  size64MediumBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  size64SemiBoldBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  size64BoldBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  size64ExtraBoldBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.6,
    fontFamily: fontFamily.extraBold,
    fontWeight: "800",
  },

  // 13px (thirteen*)
  thirteenNormalBlack: {
    ..._base,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  thirteenMediumBlack: {
    ..._base,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  thirteenSemiBoldBlack: {
    ..._base,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  thirteenBoldBlack: {
    ..._base,
    fontSize: 13,
    lineHeight: 18,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },

  // 15px (fifteen*)
  fifteenNormalBlack: {
    ..._base,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  fifteenMediumBlack: {
    ..._base,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  fifteenSemiBoldBlack: {
    ..._base,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  fifteenBoldBlack: {
    ..._base,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },

  // 17px (seventeen*)
  seventeenNormalBlack: {
    ..._base,
    fontSize: 17,
    lineHeight: 24,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  seventeenMediumBlack: {
    ..._base,
    fontSize: 17,
    lineHeight: 24,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  seventeenSemiBoldBlack: {
    ..._base,
    fontSize: 17,
    lineHeight: 24,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  seventeenBoldBlack: {
    ..._base,
    fontSize: 17,
    lineHeight: 24,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },

  // Canonical body aliases
  regular: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  medium: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  semibold: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  semiBold: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
  bold: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.bold,
    fontWeight: "700",
  },
  body: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.regular,
    fontWeight: "400",
  },
  bodyMedium: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.medium,
    fontWeight: "500",
  },
  bodySemiBold: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: fontFamily.semiBold,
    fontWeight: "600",
  },
};

export const headingTextStyles: Record<string, TextStyle> = {
  // 8px (eight*)
  eightLightBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  eightNormalBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  eightMediumBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  eightSemiBoldBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  eightBoldBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  eightExtraBoldBlack: {
    ..._base,
    fontSize: 8,
    lineHeight: 13,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 10px (ten*)
  tenLightBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  tenNormalBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  tenMediumBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  tenSemiBoldBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  tenBoldBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  tenExtraBoldBlack: {
    ..._base,
    fontSize: 10,
    lineHeight: 16,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 12px (twelve*)
  twelveLightBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  twelveNormalBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  twelveMediumBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  twelveSemiBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  twelveBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  twelveExtraBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 12px (fourteen*)
  fourteenLightBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  fourteenNormalBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  fourteenMediumBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  fourteenSemiBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  fourteenBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  fourteenExtraBoldBlack: {
    ..._base,
    fontSize: 12,
    lineHeight: 19,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 14px (sixteen*)
  sixteenLightBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  sixteenNormalBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  sixteenMediumBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  sixteenSemiBoldBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  sixteenBoldBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  sixteenExtraBoldBlack: {
    ..._base,
    fontSize: 14,
    lineHeight: 22,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 16px (eighteen*)
  eighteenLightBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  eighteenNormalBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  eighteenMediumBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  eighteenSemiBoldBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  eighteenBoldBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  eighteenExtraBoldBlack: {
    ..._base,
    fontSize: 16,
    lineHeight: 25,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 18px (twentyTwo*)
  twentyTwoLightBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  twentyTwoNormalBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  twentyTwoMediumBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  twentyTwoSemiBoldBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  twentyTwoBoldBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  twentyTwoExtraBoldBlack: {
    ..._base,
    fontSize: 18,
    lineHeight: 28,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 20px (twentyFour*)
  twentyFourLightBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  twentyFourNormalBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  twentyFourMediumBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  twentyFourSemiBoldBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  twentyFourBoldBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  twentyFourExtraBoldBlack: {
    ..._base,
    fontSize: 20,
    lineHeight: 31,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 22px (size24*)
  size24LightBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size24NormalBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size24MediumBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size24SemiBoldBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size24BoldBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size24ExtraBoldBlack: {
    ..._base,
    fontSize: 22,
    lineHeight: 35,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 24px (twentyEight*)
  twentyEightLightBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  twentyEightNormalBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  twentyEightMediumBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  twentyEightSemiBoldBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  twentyEightBoldBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  twentyEightExtraBoldBlack: {
    ..._base,
    fontSize: 24,
    lineHeight: 38,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 26px (thirty*)
  thirtyLightBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  thirtyNormalBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  thirtyMediumBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  thirtySemiBoldBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  thirtyBoldBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  thirtyExtraBoldBlack: {
    ..._base,
    fontSize: 26,
    lineHeight: 41,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 28px (size30*)
  size30LightBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size30NormalBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size30MediumBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size30SemiBoldBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size30BoldBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size30ExtraBoldBlack: {
    ..._base,
    fontSize: 28,
    lineHeight: 44,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 30px (thirtyTwo*)
  thirtyTwoLightBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  thirtyTwoNormalBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  thirtyTwoMediumBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  thirtyTwoSemiBoldBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  thirtyTwoBoldBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  thirtyTwoExtraBoldBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 32px (thirtyFour*)
  thirtyFourLightBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  thirtyFourNormalBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  thirtyFourMediumBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  thirtyFourSemiBoldBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  thirtyFourBoldBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  thirtyFourExtraBoldBlack: {
    ..._base,
    fontSize: 32,
    lineHeight: 50,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 34px (thirtySix*)
  thirtySixLightBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  thirtySixNormalBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  thirtySixMediumBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  thirtySixSemiBoldBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  thirtySixBoldBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  thirtySixExtraBoldBlack: {
    ..._base,
    fontSize: 34,
    lineHeight: 53,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 38px (size38*)
  size38LightBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size38NormalBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size38MediumBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size38SemiBoldBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size38BoldBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size38ExtraBoldBlack: {
    ..._base,
    fontSize: 38,
    lineHeight: 59,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 40px (size40*)
  size40LightBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size40NormalBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size40MediumBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size40SemiBoldBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size40BoldBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size40ExtraBoldBlack: {
    ..._base,
    fontSize: 40,
    lineHeight: 62,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 42px (size42*)
  size42LightBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size42NormalBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size42MediumBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size42SemiBoldBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size42BoldBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size42ExtraBoldBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 46px (size46*)
  size46LightBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size46NormalBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size46MediumBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size46SemiBoldBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size46BoldBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size46ExtraBoldBlack: {
    ..._base,
    fontSize: 46,
    lineHeight: 72,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 48px (size48*)
  size48LightBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size48NormalBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size48MediumBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size48SemiBoldBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size48BoldBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size48ExtraBoldBlack: {
    ..._base,
    fontSize: 48,
    lineHeight: 75,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 56px (size56*)
  size56LightBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size56NormalBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size56MediumBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size56SemiBoldBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size56BoldBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size56ExtraBoldBlack: {
    ..._base,
    fontSize: 56,
    lineHeight: 87,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  // 64px (size64*)
  size64LightBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "300",
  },
  size64NormalBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.regular,
    fontWeight: "400",
  },
  size64MediumBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.medium,
    fontWeight: "500",
  },
  size64SemiBoldBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  size64BoldBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  size64ExtraBoldBlack: {
    ..._base,
    fontSize: 64,
    lineHeight: 100,
    letterSpacing: -0.6,
    fontFamily: headingFontFamily.extraBold,
    fontWeight: "800",
  },

  thirtyTwoSemiBoldItalicBlack: {
    ..._base,
    fontSize: 30,
    lineHeight: 47,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBoldItalic,
    fontWeight: "600",
    fontStyle: "italic",
  },
  size42SemiBoldItalicBlack: {
    ..._base,
    fontSize: 42,
    lineHeight: 66,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBoldItalic,
    fontWeight: "600",
    fontStyle: "italic",
  },

  // 25px
  twentyFiveSemiBoldBlack: {
    ..._base,
    fontSize: 25,
    lineHeight: 32,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBold,
    fontWeight: "600",
  },
  twentyFiveBoldBlack: {
    ..._base,
    fontSize: 25,
    lineHeight: 32,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  twentyFiveSemiBoldItalicBlack: {
    ..._base,
    fontSize: 25,
    lineHeight: 32,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.semiBoldItalic,
    fontWeight: "600",
    fontStyle: "italic",
  },

  // 90px (Hero metric)
  ninetyBoldBlack: {
    ..._base,
    fontSize: 90,
    lineHeight: 86,
    letterSpacing: -2,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },

  // Canonical heading aliases
  h1: {
    ..._base,
    fontSize: 28,
    lineHeight: 36,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  h2: {
    ..._base,
    fontSize: 24,
    lineHeight: 32,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
  h3: {
    ..._base,
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.3,
    fontFamily: headingFontFamily.bold,
    fontWeight: "700",
  },
};

/** TextInput-safe subset of a typography preset (omits lineHeight, fixes Android padding). */
export const toTextInputTypography = (preset: TextStyle): TextStyle => ({
  fontFamily: preset.fontFamily,
  fontSize: preset.fontSize,
  fontWeight: preset.fontWeight,
  letterSpacing: preset.letterSpacing,
  ...(Platform.OS === "android"
    ? { textAlignVertical: "center", includeFontPadding: false }
    : null),
});
