export const DEFAULT_PACE_SECONDS = 600; // 10:00 per km — general shadow pace
export const MAX_SHADOW_PACE_SECONDS = 60 * 60; // 60 minutes for 1K steps
export const PACE_DECAY_RATE = 0.1; // +10% slower per complete missed race day

const unsplashPortrait = (photoId: string) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&q=80&w=400&h=400`;

const commonsFile = (fileName: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(fileName)}?width=400`;

export const OPPONENT_AVATARS = {
  bot_roshni: unsplashPortrait("photo-1573496359142-b8d87734a5a2"),
  bot_amit: unsplashPortrait("photo-1560250097-0b93528c311a"),
  bot_sarthak: unsplashPortrait("photo-1519085360753-af0119f7cbe7"),
  athlete_bolt: commonsFile("Usain_Bolt_smiling_Berlin_2009.JPG"),
  athlete_ronaldo: commonsFile(
    "Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-075_(cropped).jpg",
  ),
  athlete_kohli: commonsFile(
    "Virat_Kohli_during_the_India_vs_Aus_4th_Test_match_at_Narendra_Modi_Stadium_on_09_March_2023.jpg",
  ),
  athlete_messi: commonsFile("Leo_Messi_Argentina_v_Egypt_7_July_2026-1.jpg"),
  athlete_kipchoge: commonsFile("Eliud_Kipchoge_in_Berlin_-_2015_(cropped).jpg"),
  athlete_goggins: commonsFile("DavidGogginsMay08.jpg"),
} as const;

export const LEGENDARY_ATHLETES = [
  {
    uid: "bot_roshni",
    username: "Roshni Bansal",
    profession: "Daily Walker",
    bio: "Steady & Consistent Pace",
    profileImageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 1200,
    shadowData: {
      uid: "bot_roshni",
      username: "Roshni Bansal",
      profession: "Daily Walker",
      bio: "Steady & Consistent Pace",
      profileImageUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 1200,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "bot_amit",
    username: "Amit Nayak",
    profession: "Fitness Enthusiast",
    bio: "5K Daily Runner",
    profileImageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 1000,
    shadowData: {
      uid: "bot_amit",
      username: "Amit Nayak",
      profession: "Fitness Enthusiast",
      bio: "5K Daily Runner",
      profileImageUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 1000,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "bot_sarthak",
    username: "Sarthak Trivedi",
    profession: "Speed Walker",
    bio: "High Cadence Specialist",
    profileImageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 857,
    shadowData: {
      uid: "bot_sarthak",
      username: "Sarthak Trivedi",
      profession: "Speed Walker",
      bio: "High Cadence Specialist",
      profileImageUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 857,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "athlete_bolt",
    username: "Usain Bolt",
    profession: "Sprinter",
    bio: "8x Olympic Gold • 100m World Record Holder",
    profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Usain_Bolt_Rio_100m_final_2016.jpg/400px-Usain_Bolt_Rio_100m_final_2016.jpg",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 480,
    shadowData: {
      uid: "athlete_bolt",
      username: "Usain Bolt",
      profession: "Sprinter",
      bio: "8x Olympic Gold • 100m World Record Holder",
      profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Usain_Bolt_Rio_100m_final_2016.jpg/400px-Usain_Bolt_Rio_100m_final_2016.jpg",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 480,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "athlete_ronaldo",
    username: "Cristiano Ronaldo",
    profession: "Footballer",
    bio: "5x Ballon d'Or • Relentless Athletic Stamina",
    profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/400px-Cristiano_Ronaldo_2018.jpg",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 510,
    shadowData: {
      uid: "athlete_ronaldo",
      username: "Cristiano Ronaldo",
      profession: "Footballer",
      bio: "5x Ballon d'Or • Relentless Athletic Stamina",
      profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Cristiano_Ronaldo_2018.jpg/400px-Cristiano_Ronaldo_2018.jpg",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 510,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "athlete_kohli",
    username: "Virat Kohli",
    profession: "Cricketer",
    bio: "World Champion • Elite Fitness & Running Cadence",
    profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Virat_Kohli.jpg/400px-Virat_Kohli.jpg",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 540,
    shadowData: {
      uid: "athlete_kohli",
      username: "Virat Kohli",
      profession: "Cricketer",
      bio: "World Champion • Elite Fitness & Running Cadence",
      profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Virat_Kohli.jpg/400px-Virat_Kohli.jpg",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 540,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "athlete_messi",
    username: "Lionel Messi",
    profession: "Footballer",
    bio: "World Cup Winner • High Acceleration & Agility",
    profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lionel-Messi-Argentina-2022-World-Cup_%28cropped%29.jpg/400px-Lionel-Messi-Argentina-2022-World-Cup_%28cropped%29.jpg",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 570,
    shadowData: {
      uid: "athlete_messi",
      username: "Lionel Messi",
      profession: "Footballer",
      bio: "World Cup Winner • High Acceleration & Agility",
      profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lionel-Messi-Argentina-2022-World-Cup_%28cropped%29.jpg/400px-Lionel-Messi-Argentina-2022-World-Cup_%28cropped%29.jpg",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 570,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "athlete_kipchoge",
    username: "Eliud Kipchoge",
    profession: "Marathoner",
    bio: "Sub-2 Hour Marathon Legend • Unmatched Endurance",
    profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Eliud_Kipchoge_in_2019.jpg/400px-Eliud_Kipchoge_in_2019.jpg",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 630,
    shadowData: {
      uid: "athlete_kipchoge",
      username: "Eliud Kipchoge",
      profession: "Marathoner",
      bio: "Sub-2 Hour Marathon Legend • Unmatched Endurance",
      profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Eliud_Kipchoge_in_2019.jpg/400px-Eliud_Kipchoge_in_2019.jpg",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 630,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
  {
    uid: "athlete_goggins",
    username: "David Goggins",
    profession: "Ultra Runner",
    bio: "Navy SEAL • 100-Mile Ultra Endurance Master",
    profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/David_Goggins_speaking_at_a_conference.jpg/400px-David_Goggins_speaking_at_a_conference.jpg",
    type: "shadow",
    currentSteps: 1000,
    bestPaceSeconds: 680,
    shadowData: {
      uid: "athlete_goggins",
      username: "David Goggins",
      profession: "Ultra Runner",
      bio: "Navy SEAL • 100-Mile Ultra Endurance Master",
      profileImageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/David_Goggins_speaking_at_a_conference.jpg/400px-David_Goggins_speaking_at_a_conference.jpg",
      bestStepCount: 1000,
      originalBestStepCount: 1000,
      bestPaceSeconds: 680,
      lastActiveDate: new Date().toISOString(),
      decayRate: 0.05,
      isOnline: true,
    },
  },
];

for (const athlete of LEGENDARY_ATHLETES) {
  const avatarUrl = OPPONENT_AVATARS[athlete.uid as keyof typeof OPPONENT_AVATARS];
  if (!avatarUrl) continue;
  athlete.profileImageUrl = avatarUrl;
  if (athlete.shadowData) {
    athlete.shadowData.profileImageUrl = avatarUrl;
  }
}
